logging:
  level:
    root: info
    "[com.example.demo.**]": debug
    
spring:
  autoconfigure:
    exclude:
    # 使用druid-spring-boot-starter，但是在springboot的启动类上exclude掉DruidDataSourceAutoConfigure这个类，忽略druid连接池的默认数据源配置
    # 参考：https://www.cnblogs.com/ybyn/p/13690752.html
    - com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  sql:
    init:
      mode: never
  jpa:
    primary:
      database: POSTGRESQL
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    secondary:
      database: POSTGRESQL
      show-sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    druid:
      primary:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/test
        username: test
        password: test
        initial-size: 1
        max-active: 20
        min-idle: 1
        max-wait: 60000
        pool-prepared-statements: true
        max-open-prepared-statements: 20
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        validation-query: SELECT 1
      secondary:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/test
        username: test
        password: test
        initial-size: 1
        max-active: 20
        min-idle: 1
        max-wait: 60000
        pool-prepared-statements: true
        max-open-prepared-statements: 20
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        validation-query: SELECT 1
